language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

install:
  - composer install --dev --prefer-source

script: phpunit -c tests/phpunit.xml tests

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm