language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - '7'
  - nightly
  - hhvm

install:
  - composer install --dev --prefer-source

script: phpunit --coverage-text --coverage-clover ./build/logs/clover.xml tests

after_script:
  - php vendor/bin/coveralls

matrix:
  fast_finish: true
  allow_failures:
    php:
      - nightly
      - '7'
      - hhvm